### ISSUE TITLE
Feature: Allow chaining numeric comparisons

### ISSUE THREAD

**Issue by scheibling** [jtlabsio/mongo#6]
We're currently using this library for product filtration, and would need something like this to be able to filter products that fall within a certain price range. After having tried out a couple of different options, the best solution seems to be adding the ability to chain comparisons for the numeric fields like this:

?filter[price]=<=1400,>=1500

That way, we wouldn't introduce any breaking changes and keep a similar syntax as today. Another method would be chaining requests like ?filter[price]=>=1400&?filter[price]=<=1500, but that would require some changes to the URI query parser as well and the comma-based syntax would be consistent with the filter[x]=a,b,c variant

Working on a PR, will upload for review shortly

**Comment by scheibling** [comment]
See #7 , not the cleanest solution but would give some leeway for applications to chain multiple operators of the same type in the query (now whether that's a good or bad thing remains to be seen).

**Comment by brozeph** [comment]
Proposing <https://github.com/jtlabsio/mongo/pull/8> that builds on top of @scheibling 's excellent initial work here. Fleshed out unit tests and further cleaned up a few over uses of `bson.D` wrapping `bson.E` objects to keep the resulting queries a bit cleaner.

**Comment by brozeph** [comment]
@scheibling please checkout v1.5.1 now... this should allow chaining with comparisons on both numbers and dates!

**Comment by scheibling** [comment]
Wonderful, works a lot better than my cobbled-together version :-) Thank you ever so much for your help!
